# Generated by Django 4.2.13 on 2024-06-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0005_createdResultModel'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='pass_percent',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_duration',
            field=models.IntegerField(default=30),
        ),
    ]
